### ISSUE TITLE
请问这是什么原因？

### ISSUE THREAD

**Issue by bd5dml77** [guohuadeng/odoo11-x64#1]
h:\odoo11-x64-master>h:\odoo11-x64-master\runtime\python3\python3 h:\odoo11-x64-master\source\odoo-bin -c h:\odoo11-x64-master\odoo.conf --update=""
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00001f28 (most recent call first):

**Comment by GoodERPJeff** [comment]
估计 python3 目录下的 encodings 目录被删了

**Comment by guohuadeng** [comment]
add
